### ISSUE TITLE
Bug on SAI, or Android?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Aefyr/SAI#125]
I've noticed a weird behavior, which happens not just on SAI, but on a POC I've made, so as I believe it's a bug on Android (including Android R), I reported about this here: 
https://issuetracker.google.com/issues/154212612

Once you get to the dialog that asks if it's ok to install, instead of choosing to install, if you press outside of the dialog, or you press the back key, you won't get a callback.
And I tried to use `startActivityForResult` instead, but then you will always get `RESULT_CANCELED` for `onActivityResult`. 

And on SAI, it seems to also occur. If I do this, the app says it's still "installng", forever...

Is there any way to overcome this? Any workaround?

**Comment by Aefyr** [comment]
Yeah, I've just checked it on R emulator and tapping outside dialog just closes it indeed. Pressing back cancels the installation in my case though. Since result in onActivityResult is just RESULT_CANCELLED with null data regardless of what user does in the prompt, I don't think there's a workaround for it. Hopefully AOSP devs notice your issue on their tracker.

I've also checked your second issue with app going in background after user allows app installing apps from it. It not just goes in background, it actually gets killed which in SAI's case resets installer state. The reason it gets killed according to log, is because REQUEST_INSTALL_PACKAGES permission changes. Here's the log entry:
```
2020-04-18 14:52:28.212 2249-2296/? I/ActivityManager: Force stopping com.aefyr.sai.fdroid appid=10147 user=-1: REQUEST_INSTALL_PACKAGES changed.
```
But Android normally only kills apps when user revokes permissions, not grants them. However I'm not sure if this is a bug or intentional behavior

**Comment by AndroidDeveloperLB** [comment]
About the "onActivityResult " , ok.

I don't understand the other issue you talk about. Please show a link.
You talk about Android R weird glitches, right? You say that the process is dead just because the permission was granted?
Can you please write on it for Google to read there?

**Comment by Aefyr** [comment]
> I don't understand the other issue you talk about. Please show a link.

I mean [this issue](https://issuetracker.google.com/u/1/issues/154157387). I've replied there.



> You talk about Android R weird glitches, right? You say that the process is dead just because the permission was granted?

Well, I'm not sure if this is a glitch or intentional, but yeah, the app process gets killed when user allows to install apps from it.

**Comment by AndroidDeveloperLB** [comment]
Yes sorry for that. I wrote a lot of issues lately and also replied to (very) old ones that Google decided to handle only recently. Easy to confuse between them

**Comment by AndroidDeveloperLB** [comment]
Please consider to also star the issues.

**Comment by Aefyr** [comment]
Done.

**Comment by AndroidDeveloperLB** [comment]
@github-actions Too late. I closed it now instead!
The issue itself still remains though, but on Android's side.

**Comment by AndroidDeveloperLB** [comment]
And another, very similar one:
https://github.com/Aefyr/SAI/issues/170
