### ISSUE TITLE
Internal file picker doesn't detect SD card

### ISSUE THREAD

**Issue by AinzTheSupremeOne** [Aefyr/SAI#194]
It looks like SAI only opens internal storage if I click on Internal file picker. Would be nice if SD card could be accessed. Is this intended or a bug?  Can't it use SAF/scoped storage to access SD card?

**Comment by AinzTheSupremeOne** [comment]
Note that files on SD card still be accessed from using System file picker.

**Comment by AinzTheSupremeOne** [comment]
Also, this pro mode error might be related. If I select an apks file from internal storage, SAI can can successfully parse it and show me the option to select specific splits. But if I move the apks to SD card and then select it, SAI shows this error. 
![Screenshot_2021-02-05-18-54-32-301_com aefyr sai](https://user-images.githubusercontent.com/50095635/107039269-a9dcf780-67e3-11eb-81c0-0a086d0bc31b.jpg)
![Screenshot_2021-02-05-18-51-21-852_com aefyr sai](https://user-images.githubusercontent.com/50095635/107039272-ac3f5180-67e3-11eb-8516-e250674a16bc.jpg)

**Comment by Aefyr** [comment]
> Can't it use SAF/scoped storage to access SD card?

Internal file picker just uses File IO and READ_EXTERNAL_STORAGE permission. Due to scoped storage (and the fact that you can't use the access all files permission on Android 11 for file selection according to Google Play guidelines), I'm not planning on improving the internal file picker. System file picker will become the only option on Android 11 and up as soon as SAI moves to target API of 30 (which will happen when it is required by Google Play)




> But if I move the apks to SD card and then select it, SAI shows this error.

If you mean this happens when you use system file picker, this is probably due to an issue in DocumentsUI (aka system file picker) on Android 6 and below (or 7 and below, can't remember). Try installing a 3rd party file manager that supports SAF such as Solid Explorer and selecting it in the side bar thingy in DocumentsUI then choosing files there, the 3rd party file manager should grant proper permissions for selected files to SAI

**Comment by AinzTheSupremeOne** [comment]
> If you mean this happens when you use system file picker, this is probably due to an issue in DocumentsUI (aka system file picker) on Android 6 and below (or 7 and below, can't remember). Try installing a 3rd party file manager that supports SAF such as Solid Explorer and selecting it in the side bar thingy in DocumentsUI then choosing files there, the 3rd party file manager should grant proper permissions for selected files to SAI

Well same results 
Screen recording is there. And I am on Android Q.
https://mega.nz/file/v6QzlQpI#ZTOXN8u7Ewz88GXR-lRwFQn7fCrptezztT98g2rKzxg

**Comment by Aefyr** [comment]
> Well same results
> Screen recording is there. And I am on Android Q.
> https://mega.nz/file/v6QzlQpI#ZTOXN8u7Ewz88GXR-lRwFQn7fCrptezztT98g2rKzxg . I can share logcat if you need them.

Yeah, I've tried it on Android 11 emulator, it doesn't work there as well. Guess Google broke the /proc/self/fd thing with scoped storage. Tbh no idea what to do about this, seems like the only solution is copying files

**Comment by AinzTheSupremeOne** [comment]
Oh I see, so could this workaround be implemented? 🤔

**Comment by Aefyr** [comment]
I did add copying when permssion is denied in https://github.com/Aefyr/SAI/commit/6430a42900b479205f8a6c23833897fb7deccb29 for files up to 100MBs

**Comment by JohnRTitor** [comment]
Closing this based on the above discussion and the fix has been implemented.
