### ISSUE TITLE
SAI fail to parse APKM files

### ISSUE THREAD

**Issue by chromer030** [Aefyr/SAI#195]
latest SAI fail to parse APKM files, while apps like APK Combo installer parse and install same file successfully.
(APKM is downloaded from apkmirror and it's not encrypted.)

APKM URL :

https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-24-0-32-release/google-play-store-24-0-32-21-0-pr-356387442-android-apk-download/download/

![Screenshot_20210211-190450](https://user-images.githubusercontent.com/13361552/107659926-f1a8c680-6c9c-11eb-8dd3-7e5fe9f124f5.png)

## (Installing file anyway crashed the app.)

**Comment by Aefyr** [comment]
Yeah, it caused by scoped storage, I've added a workaround (copying files to parse them) in https://github.com/Aefyr/SAI/commit/6430a42900b479205f8a6c23833897fb7deccb29. Crashing when installing anyway is weird tho, can you provide your device model so I can search Crashlytics logs? Or you can use logcat to capture crash log if you know how to do it.

**Comment by chromer030** [comment]
My device is Lenovo K3 Note using Android 7.1.2 arm64
I will take and send logcat soon.

**Comment by chromer030** [comment]
i think crash problem is about my device or android , because i tested on another device with android 10 : App didn't crashed , Despite of parser error app successfully installed apkm.
