### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RUDRA7074** [Aefyr/SAI#218]
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.vanced.android.youtube signatures do not match previously installed version; ignoring!

**Comment by Exanoff12** [comment]
hello @RUDRA7074, the package you are trying to install is vanced YouTube (com.vanced.android.youtube) . and if you didn't know to install vanced YouTube you need to flash microG using twrp on your rooted android phone. so if you haven't dont these steps the file installation will fail. beacuse original YouTube has a specific signature by Google in its app which can't be copied/erased and vanced YouTube has a different signature by the creator of vanced himself and they will not match. when you install vanced YouTube it needs to at first remove the YouTube app itself which isn't possible without root and microG. so that should get it cleared.
