### ISSUE TITLE
How do I select files on external sdcard with "internal file selection"?

### ISSUE THREAD

**Issue by RichardBeisser** [Aefyr/SAI#286]
Hello,

how do I select files with "internal file selection" which are stored on external sdcard?
With "system file selection" you can navigate to files outside "interal storage", but you cannot select more than 1 file for installation. This is not suitable to splitted apks.

Thanks.

**Comment by agret** [comment]
There's two ways to do it:

First method -- Navigate to the folder using system file selection and instead of tapping on your file hold down on it for a few seconds and then you can tick to select multiple files at once.

Second method -- Zip all of the files that make up the split apk into a single zip file then rename it to .apks and pick that with the system file selection.
