### ISSUE TITLE
Allocation Issue

### ISSUE THREAD

**Issue by OmerFlame** [Aefyr/SAI#32]
Hi,

for some reason I can't install split APKs. It always gives me an "allocation problem". My phone is not rooted, a Samsung Galaxy J6 2018 (J600G). What should I do?

**Comment by Aefyr** [comment]
What the exact error text? There's no error description that says"allocation problem" in SAI (unless it's some kind of system warning rather then a SAI one). 
The problem is likely with Samsung J-series devices, I've seen quite a bit of complaints from users of those on GP. I think the only thing you can really do is to get root/change ROM.
