### ISSUE TITLE
Install to external storage (SD card)

### ISSUE THREAD

**Issue by Rikk** [Aefyr/SAI#50]
Is there a way in the app to force installation to external storage (SD card)?

Traditionally I used package manager `pm install -s` in order to install an app directly into extSD. It is also possible for installing these bundle split apks? Could you please implement an option in SAI app?

Thank you!

**Comment by Aefyr** [comment]
Does setting install location to prefer external not work? If so, I don't think forcing it would be a good idea since there must be a reason Android doesn't want to install it to external storage.

**Comment by Rikk** [comment]
Looking at su logs, I see SAI relies on `--install-location` parameter, which doesn't exist in the `pm` of my Android 5. According to the help of pm, `-s` parameter is the one that installs on SD. Therefore, it always install into internal.
```
pm install-create -r --install-location 2 -i 'com.aefyr.sai'
MError: java.lang.IllegalArgumentException: Unknown option --install-location
```

**Comment by Aefyr** [comment]
Does rootless mode not work on your device? In rootless mode, install location is supported on Android 5

**Comment by Rikk** [comment]
Doesn't work...
```
Your ROM is incompatible with rootless installer. Try selecting another installer in SAI settings.
```
Other than this error, it also leaves a tmp folder in /data/app

**Comment by Aefyr** [comment]
Well, I made an option to enter custom install-create command in the Super Secret Settings (Which you can access by tapping SAI logo on about screen 3+ times and then long-tapping it). Here's a debug build (inside a ZIP because GitHub doesn't allow attaching APKs directly), you can try entering `pm install-create -r -s`  there
[app-fdroid-debug.zip](https://github.com/Aefyr/SAI/files/3800913/app-fdroid-debug.zip)

**Comment by Aefyr** [comment]
You should also provide `-i com.aefyr.sai.fdroid` argument as well because currently rooted/Shizuku installer in SAI relies on the `ACTION_PACKAGE_ADDED` broadcast and checks the installer app package there to determine when an app has been installed, so it would hang forever without that argument.

In the build above however there's a bug that I've just found and fixed which would cause it to accept a `ACTION_PACKAGE_ADDED` when installer app is null, so installation without that argument works in that build.

**Comment by Rikk** [comment]
Strange, I'm only getting this error when using `pm install-create -s` (I also tested in command line). It only happens when `-s` parameter is used.
```
Error: java.lang.IllegalStateException: ☃No storage with enough free space; res=-1
```
Granted, I remember it didn't trigger error some other time I tried the command. Dunno what is causing it...

**Comment by Aefyr** [comment]
Android really doesn't want you to install that app to external storage I guess

**Comment by Rikk** [comment]
> Android really doesn't want you to install that app to external storage I guess

Not related to the app. Just `pm install-create -s` on command line also errors out. Something is strange about my "pm"
