### ISSUE TITLE
java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor

### ISSUE THREAD

**Issue by tienquanutc** [Aefyr/SAI#98]
**Description**:  I'm getting the error *java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor* when trying install zip file.
**Cause**: ZipInputStream throws a ZipException (with message "only DEFLATED entries can have EXT descriptor") when there is a zero-length entry and the compression method is not set to DEFLATE.
**Solution**: https://stackoverflow.com/questions/47208272/android-zipinputstream-only-deflated-entries-can-have-ext-descriptor
**Sample file**: [Netflix_v7.48.0 build 10 34747.zip](https://github.com/Aefyr/SAI/files/4343980/Netflix_v7.48.0.build.10.34747.zip)

 I hope this problem is resolved as soon as possible.

**Comment by Aefyr** [comment]
That's not really a solution because SAI gets input files as streams, because SAF and stuff (see [FileDescriptor](https://github.com/Aefyr/SAI/blob/master/app/src/main/java/com/aefyr/sai/model/filedescriptor/FileDescriptor.java) and [ZipApkSource](https://github.com/Aefyr/SAI/blob/master/app/src/main/java/com/aefyr/sai/model/apksource/ZipApkSource.java)). The only way to use ZipFile in this case would be to create an ApkSource implementation that copies the file from a FileDescriptor to a temp file and then opens it via ZipFile.
As long as you're fine with the overhead of copying source file, I can implement it as a setting, but is that really necessary when you can just create proper archives in the first place?

**Comment by tienquanutc** [comment]
Thank you for explaining me.
Most websites download apk as [APKPure](https://apkpure.com) or [APKCombo](https://apkcombo.com) stream zip on fly to avoid zip file compression, maybe when it zipped, the cost of updating the zip file is huge. SAI will face this problem when trying to install zip from them. I hope you can implement this feature as a fallback when DEFLATED ZipException was thrown.
The sample is a zip file from APKPure, you can check with it.

**Comment by Aefyr** [comment]
Implementing fallback is not trivial, because of all of the states the session can be when exception occurs. The best possible solution would be to re-enqueue failed session with an ApkSource that will use ZipFile, but then installers will have to know about SAI settings (such as signing) to build a proper ApkSource, which doesn't sound nice. Anyway, I'll at least add a setting for that and a message to enable it on error, maybe I'll come up with a better idea by the time I start implementing it.

**Comment by phingocchi** [comment]
You can implement SAI extract the APK files from ZIP File to the "temporary folder" without ZipInputStream and install the APK files from the temporary folder.

**Comment by Aefyr** [comment]
In the end I couldn't find a good way to handle that exception and [it just throws a ZipException telling user to enable "Use ZipFile API" toggle in ZipApkSource](https://github.com/Aefyr/SAI/blob/18b527b6c76d1b4f95b2de5d15efd35d6d4ecef8/app/src/main/java/com/aefyr/sai/model/apksource/ZipApkSource.java#L47)

**Comment by Aefyr** [comment]
@phingocchi SAI gets input archives as a stream, that's why it normally uses ZipInputStream. To use ZipFile I had to first copy that stream to a temp file and then open it via ZipFile, check [this comment](https://github.com/Aefyr/SAI/issues/98#issuecomment-600175116) and the new [ZipFileApkSource](https://github.com/Aefyr/SAI/blob/master/app/src/main/java/com/aefyr/sai/model/apksource/ZipFileApkSource.java)
